default_stages: [commit]
repos:
  - repo: local
    hooks:

      - id: black
        name: Black
        entry: black
        types: [python]
        language: system

      - id: system
        name: Isort
        entry: isort
        types: [python]
        language: system

      - id: pycodestyle
        name: Pycodestyle
        entry: pycodestyle
        args:
          [
            "--config=pyproject.toml",
          ]
        types: [python]
        language: system

      - id: pylint
        name: Pylint
        entry: pylint
        args:
          [
            "--rcfile=pyproject.toml",
          ]
        types: [python]
        language: system

      - id: pydocstyle
        name: pydocstyle
        entry: pydocstyle
        types: [python]
        language: system
