site_name: '🐍 Python for Machine Learning Course'
repo_url: https://github.com/Matesanz/python_machine_learning_course
repo_name: Matesanz/python_machine_learning_course
theme:
  name: material
  theme:
  palette:
    primary: teal
  features:
    - content.code.annotate
    - navigation.tracking
    - navigation.tabs
    - navigation.prune
    - navigation.indexes

plugins:
  - search
  - autorefs
  - mkdocstrings:
      handlers:
        python:
          options:
            separate_signature: true
  - mkdocs-jupyter


markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

watch:
  - 'python_ml_course'
  - docs
