name: Semantic Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install python-semantic-release

    - name: Create release branch
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git checkout -b release

    - name: Run Semantic Release
      run: |
        semantic-release version
        git commit -am "chore(release): release version"
        git push origin release

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: "Release version"
        body: "New version is ready to be merged"
        branch: "release"

    - name: Auto approve
      uses: hmarr/auto-approve-action@v2.0.0
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"

    - name: Merge Pull Request
      uses: pascalgn/automerge-action@v0.14.2
      env:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        MERGE_LABELS: ""
        MERGE_METHOD: "squash"
        MERGE_COMMIT_MESSAGE: "Automatic merge of release version"
        MERGE_FORKS: "false"
        UPDATE_LABELS: ""
